spring.application.name=restapi

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always

management.prometheus.metrics.export.enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver